metadata:
  engine: 4.1
  version: 0.1
  author: Carter Pollan
  contact: carter.pollan@gmail.com
  
units:
  default_stagger: 0
  default_spread: 'cx'
  default_splay: 0
  default_height: 'cx-1'
  default_width: 'cy-1'
  default_padding: 'cx'
  default_autobind: 10
  kx: cx
  ky: cy - 7
  px: cx - 7
  py: ky
  ledy: -cx/2 + 3
  feet_rad: 2

points:
  zones:
    matrix:
      key:
        padding: cy
        spread: cx
      anchor:
        rotate: 5
        shift: [150, -100]
      columns:
        pinky:
          key:
            col_net: P0
        ring:
          key:
            splay: -5
            origin: [-12, -19]
            stagger: 12
            col_net: P1
        middle:
          key:
            stagger: 5
            col_net: P2
        index:
          key:
            stagger: -6
            col_net: P3
        inner:
          key:
            stagger: -2
            col_net: P4
      rows:
        bottom:
          row_net: P6
        home:
          row_net: P7
        top:
          row_net: P8
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
          key:
            col_net: P2
        home:
          key:
            spread: 21.25
            splay: -28
            origin: [-11.75, -9]
            col_net: P3
        far: 
          key:
            spread: 21.25
            splay: -28
            origin: [-9.5, -9]
            col_net: P4
      rows:
        thumb:
          row_net: P5
  rotate: -15

outlines:
  keys:
  - what: rectangle
    where: true
    size: [cx-.1, cy-.1]
  board:
  - what: polygon
    operation: stack
    fillet: 3
    points:
    - ref: matrix_pinky_top
      shift: [-px, py]
    - ref: matrix_ring_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx*4/2 - 5, py]
    - ref: matrix_inner_bottom
      shift: [cx*4/2 - 5,-cy/2]
    - ref: thumbfan_far_thumb
      shift: [px, py]
    - ref: thumbfan_far_thumb
      shift: [px, -py]
    - ref: thumbfan_home_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_home_thumb
      shift: [-cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [-cy/2, -py]
    - ref: matrix_pinky_bottom
      shift: [-px, -py]
  faceplateKeys:
  - what: rectangle
    where: true
    size: [14,14]
  faceplateOutline:
  - what: polygon
    operation: stack
    fillet: 3
    points:
    - ref: matrix_pinky_top
      shift: [-px, py]
    - ref: matrix_ring_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_bottom
      shift: [cx/2, -cy/2]
    - ref: matrix_inner_bottom
      shift: [cx*4/2 - 5,-cy/2]
    - ref: thumbfan_far_thumb
      shift: [px, py]
    - ref: thumbfan_far_thumb
      shift: [px, -py]
    - ref: thumbfan_home_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_home_thumb
      shift: [-cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [-cy/2, -py]
    - ref: matrix_pinky_bottom
      shift: [-px, -py]
  faceplate:
  - name: faceplateOutline
  - operation: subtract
    name: faceplateKeys
  case_inner:
  - name: board
    expand: .7
  case_outer:
  - name: board
    expand: 3
  case_edge:
  - name: case_outer
  - operation: subtract
    name: case_inner

  case_feet_one:
  - what: circle
    where:
    - ref: matrix_pinky_top
      shift: [-cx/2,cy/2]
    radius: feet_rad
  case_feet_two:
  - what: circle
    where:
    - ref: matrix_inner_top
      shift: [cx*3/2+2,cy/2]
    radius: feet_rad
  case_feet_three:
  - what: circle
    where:
    - ref: thumbfan_far_thumb
      shift: [cx/2,cx/2]
    radius: feet_rad
  case_feet_four:
  - what: circle
    where:
    - ref: thumbfan_far_thumb
      shift: [cx/2,-cx/2]
    radius: feet_rad
  case_feet_five:
  - what: circle
    where:
    - ref: matrix_pinky_bottom
      shift: [-cx/2,-cx/2]
    radius: feet_rad

  case_outer_feet:
  - name: case_outer
  - operation: subtract
    name: case_feet_one
  - operation: subtract
    name: case_feet_two
  - operation: subtract
    name: case_feet_three
  - operation: subtract
    name: case_feet_four
  - operation: subtract
    name: case_feet_five

pcbs:
  boardPcb:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: custom/footprints/choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          traces: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: custom/footprints/diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [3, -(cy/2 - 1.2)]
          rotate: 0
      microcontroller:
        what: custom/footprints/seeed_xaio
        params:
        where:
          ref: matrix_inner_top
          shift: [2*px - 2, -.5]
      audio:
        what: trrs
        params:
          A: "VCC"
          B: "GND"
          C: "P9"
          D: "P10"
          reverse: true
        where:
          ref: matrix_inner_bottom
          shift: [px*2 + 9, -3]
          rotate: -90

cases:
  faceplate:
  - what: outline
    name: faceplate
    extrude: 1
  case:
  - what: outline
    name: case_outer_feet
    extrude: -1
    operation: add
  - what: outline
    name: case_outer
    extrude: 1
  - what: outline
    name: case_edge
    extrude: 5