metadata:
  engine: 4.1
  version: 0.1
  author: Carter Pollan
  contact: carter.pollan@gmail.com
units:
  default_stagger: 0
  default_spread: 'cx'
  default_splay: 0
  default_height: 'cx-1'
  default_width: 'cy-1'
  default_padding: 'cx'
  default_autobind: 10
  kx: cx
  ky: cy - 7
  px: cx - 7
  py: ky
  ledy: -cx/2 + 3
points:
  zones:
    matrix:
      key:
        padding: cy
        spread: cx
      anchor:
        rotate: 5
        shift: [150, -100]
      columns:
        pinky:
          key:
            column_net: P1
            row_net: P2
        ring:
          key:
            splay: -5
            origin: [-12, -19]
            stagger: 12
            column_net: P3
            row_net: P4
        middle:
          key:
            stagger: 5
            column_net: P5
            row_net: P6
        index:
          key:
            stagger: -6
            column_net: P7
            row_net: P8
        inner:
          key:
            stagger: -2
            column_net: P10
            row_net: P16
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
          key:
            row_net: P6
            column_net: P14
        home:
          key:
            spread: 21.25
            splay: -28
            origin: [-11.75, -9]
            row_net: P8
            column_net: P14
        far:
          key:
            spread: 21.25
            splay: -28
            origin: [-9.5, -9]
            row_net: P16
            column_net: P14
      rows:
        thumb:
  rotate: -15
outlines:
  keys:
  - what: rectangle
    where: true
    size: [cx-.1, cy-.1]
  board:
  - what: polygon
    operation: stack
    fillet: 3
    points:
    - ref: matrix_pinky_top
      shift: [-px, py]
    - ref: matrix_ring_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx*4/2, py]
    - ref: matrix_inner_bottom
      shift: [cx*4/2, -cy/2]
    - ref: thumbfan_far_thumb
      shift: [px, py]
    - ref: thumbfan_far_thumb
      shift: [px, -py]
    - ref: thumbfan_home_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_home_thumb
      shift: [-cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [-cy/2, -py]
    - ref: matrix_pinky_bottom
      shift: [-px, -py]
  combo:
  - name: board
  - operation: subtract
    name: keys
pcbs:
  boardPcb:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      switch_via:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, cy/2]
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [cy/2 -.7, -3]
          rotate: 90
      microcontroller:
        what: custom/footprints/seeed_xiao
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [2*px, -8]
          rotate: -90
      audio:
        what: trrs
        params:
          A: "audioA"
          B: "GND"
          C: "VCC"
          D: "P9"
          reverse: true
        where:
          ref: matrix_inner_home
          shift: [px*2, -10]
          rotate: -90
      test: 
        what: mountinghole
        where: 
          ref: matrix_inner_home
      rgbB:
        what: rgb
        params:
          side: "B"
          din: "din"
          dout: "dout"
        where: true
        adjust:
          shift: [0, ledy]
      rgbF:
        what: rgb
        params:
          side: "F"
          din: "din"
          dout: "dout"
        where: true
        adjust:
          shift: [0, ledy]
cases:
  baseCase:
  - what: outline
    name: board
    extrude: 1